### ISSUE TITLE
other failure `io error: unexpected end of file`

### ISSUE THREAD

**Issue by IFmiss** [geph-official/geph4#18]
登陆报错了
![image](https://user-images.githubusercontent.com/17402583/118105333-d4f06c00-b40e-11eb-9648-0bf3b801a144.png)

v 4.4.1
mac os 11.4 Beta版(20F5065a)

**Comment by ITSRW** [comment]
Same here! 
Is this going to be a big problem? I start to worry about that  geph will be defeated by the GFW soon....
